version: '3.4'
services:
    spaceboo:
        container_name: spaceboo
        build: .
        ports:
            - 8000
        volumes:
            - .:/code
        networks:
            - spaceboo-network
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        container_name: database
        image: 'postgres:13'
        ports:
            - 5432
        restart: always
        volumes:
            - './postgres-data:/var/lib/postgresql/data'
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        networks:
            - spaceboo-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
networks:
    spaceboo-network:
        external: true
